### ISSUE TITLE
docker error with fs.js

### ISSUE THREAD

**Issue by t0mst0ne** [audreyt/ethercalc#170]
uname -a
Linux 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Docker version 1.0.1, build 990021a

sudo docker logs audreyt/ethercalc:latest

fs.js:653
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EACCES, permission denied '/.pm2'
    at Object.fs.mkdirSync (fs.js:653:18)
    at Object.CLI.pm2Init (/usr/local/lib/node_modules/pm2/lib/CLI.js:34:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:19:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

docker logs readis  redis:latest 

[1] 05 Mar 03:52:12.842 # Server started, Redis version 2.8.19
[1] 05 Mar 03:52:12.843 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[1] 05 Mar 03:52:12.843 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
[1] 05 Mar 03:52:12.843 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[1] 05 Mar 03:52:12.843 * The server is now ready to accept connections on port 6379

**Comment by audreyt** [comment]
OK, please try upgrading Docker to 1.5 first:

https://docs.docker.com/installation/ubuntulinux/

and then check out the latest image:

```bash
sudo docker run --name redis -d -v /var/lib/redis:/data redis:latest redis-server --appendonly yes
docker pull audreyt/ethercalc
sudo docker run -d -p 8000:8000 --link redis:redis audreyt/ethercalc
```

I've just verified it and it should work.
