### ISSUE TITLE
Trying to delete spreadsheet through proxy throws error

### ISSUE THREAD

**Issue by sed-sytarchuk** [audreyt/ethercalc#223]
We have our ethercalc instance passed through a proxy.

I can add sheets fine, rename sheets and change cell contents fine.

However when I try to delete a spreadsheet, a window pops up with the number 4994.

In the logs, this exception is thrown.

/usr/local/lib/node_modules/ethercalc/main.js:468
                    return DB.multi().del("snapshot-" + backupKey).rename("sna
                                                                   ^
TypeError: undefined is not a function
  at /usr/local/lib/node_modules/ethercalc/main.js:468:68
  at Array.cmds.exec (/usr/local/lib/node_modules/ethercalc/db.js:164:13)
  at /usr/local/lib/node_modules/ethercalc/db.js:160:21
  at RedisClient.Commands.get (/usr/local/lib/node_modules/ethercalc/db.js:100:44)
  at Array.cmds.exec (/usr/local/lib/node_modules/ethercalc/db.js:158:21)
  at /usr/local/lib/node_modules/ethercalc/main.js:459:50
  at Object.SC._get (/usr/local/lib/node_modules/ethercalc/sc.js:225:16)
  at /usr/local/lib/node_modules/ethercalc/main.js:443:21
  at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ethercalc/main.js:357:18)
  at IncomingMessage.emit (events.js:104:17)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

**Comment by audreyt** [comment]
Thanks for the correction — it wasn't working without a Redis server.

Fixed and published as of ethercalc@0.20150603.1 on npm.
