### ISSUE TITLE
RangeError:  Invalid String Length

### ISSUE THREAD

**Issue by JustRaze** [audreyt/ethercalc#303]
Hey Audrey - Ethercalc is crashing for me and giving the following error:

```
/usr/lib/node_modules/ethercalc/node_modules/zappajs/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:433
      strLen += '' + bufferTail[i];
              ^
RangeError: Invalid string length
  at Object.exports.decodePayloadAsBinary (/usr/lib/node_modules/ethercalc/node_modules/zappajs/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:433:20)
  at Object.exports.decodePayload (/usr/lib/node_modules/ethercalc/node_modules/zappajs/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:271:20)
  at XHR.Polling.onData (/usr/lib/node_modules/ethercalc/node_modules/zappajs/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:196:10)
  at IncomingMessage.onEnd (/usr/lib/node_modules/ethercalc/node_modules/zappajs/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)
  at IncomingMessage.emit (events.js:104:17)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

I am running Node v0.12.9 with Redis-server v=2.8.14 on an AWS m4.large EC2 instance (m4.large (6.5 ECUs, 2 vCPUs, 2.4 GHz, Intel Xeon E5-2676v3, 8 GiB memory, EBS only).

Brian

**Comment by audreyt** [comment]
Yeah, it seems we have issues with node v0.12.x. This will need to be handled by a Zappajs upgrade.

**Comment by JustRaze** [comment]
Thanks Audrey!  Is that something I can handle on my end or does it need to be incorporated into the Ethercalc base code?

**Comment by audreyt** [comment]
Try downgrading Node.js to 0.10, or upgrading to Node 4.x, and see if the issue re-occurs?

The upgrade to newer Zappa.js will need to occur in the Ethercalc base code — contributions welcome.

Cheers,
Audrey
