### ISSUE TITLE
Cross-sheet references quickly exhaust node's cpu usage

### ISSUE THREAD

**Issue by gazeto** [audreyt/ethercalc#387]
I keep receiving an error on my ethercalc (Redis) even without any activity really:

```
gazeto@praseodym ~ $ ethercalc
Please connect to: http://praseodym:8000/
Starting backend using webworker-threads
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Connected to Redis Server: localhost:6379
join [log-frisbee.2] [user-0.7029016611118681]
join [log-frisbee.5] [user-0.14773642406968812]
join [log-frisbee.1] [user-0.7736120801937277]
join [log-frisbee.2] [user-0.28072997214977047]
join [log-frisbee.6] [user-0.094123794779026]
join [log-frisbee.6] [user-0.08703456149017985]
join [log-frisbee.7] [user-0.7970069377561203]
join [log-frisbee.5] [user-0.6230744353301626]
join [log-frisbee.1] [user-0.5671424737872547]
join [log-frisbee.3] [user-0.9880527301834992]
join [log-frisbee.4] [user-0.7775541150346232]
join [log-frisbee.3] [user-0.9528378065617098]
join [log-frisbee.4] [user-0.518483451019684]
join [log-frisbee.7] [user-0.3611158603708622]



#
# Fatal error in ../deps/v8/src/api.h, line 297
# CHECK(allow_empty_handle || that != __null) failed
#

Trace/Breakpoint ausgelöst
gazeto@praseodym ~ $
```

A similar (same?) problem was described [here](https://github.com/audreyt/node-webworker-threads/issues/30) but that doesn't actually help me.

**Comment by gazeto** [comment]
The issue is irrespective of whether redis or or JSON is used.
Once appearing with a new pad, it keeps returning only a few seconds after starting ethercalc.

**Comment by audreyt** [comment]
Hmm. What is your Node.js version? Does upgrading to 6.2.2 (or downgrading to 4.4.7) help?

**Comment by gazeto** [comment]
Thanks you audreyt.
I upgraded to 6.2.2 and the problem changed but didn't resolve.

Now I (once in a while) get the following errors:

## 1. Using JSON
```
gazeto@praseodym ~ $ ethercalc
Please connect to: http://praseodym:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
  at RedisClient.on_error (/home/gazeto/node_modules/ethercalc/node_modules/redis/index.js:196:24)
  at Socket.<anonymous> (/home/gazeto/node_modules/ethercalc/node_modules/redis/index.js:106:14)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at emitErrorNT (net.js:1272:8)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

==> Falling back to JSON storage: /home/gazeto/dump.json
==> Restored previous session from JSON file

#####some usual join, disconnect etc#####

<--- Last few GCs --->

  204232 ms: Mark-sweep 397.3 (1434.9) -> 397.0 (1434.9) MB, 1026.5 / 0 ms [allocation failure] [GC in old space requested].
  205271 ms: Mark-sweep 397.0 (1434.9) -> 397.0 (1434.9) MB, 1038.1 / 0 ms [allocation failure] [GC in old space requested].
  206368 ms: Mark-sweep 397.0 (1434.9) -> 397.0 (1434.9) MB, 1096.9 / 0 ms [last resort gc].
  207469 ms: Mark-sweep 397.0 (1434.9) -> 397.0 (1434.9) MB, 1101.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24e0275c9e59 <JS Object>
    1: /* anonymous */ [evalmachine.<anonymous>:6012] [pc=0x340d6fb321ba] (this=0x18721f1644e9 <JS Global Object>)
    5: runInContext [vm.js:~42] [pc=0x340d6ad22d33] (this=0x417d1f39489 <an Object with map 0x102b5000d581>,code=0x34fcc5628a99 <Very long string[951622]>,contextifiedSandbox=0x98d1a699ed1 <an Object with map 0x102b500f4791>,options=0x24e027504189 <undefined>)
    6: arguments adap...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Abgebrochen
gazeto@praseodym ~ $
```

## 2. Using redis: 
```
gazeto@praseodym ~ $ ethercalc
Please connect to: http://praseodym:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Connected to Redis Server: localhost:6379

#####some usual join, disconnect etc#####

evalmachine.<anonymous>:4155
   if (style.length==0) return 0; // null means use zero, which means default or global default
            ^
TypeError: Cannot read property 'length' of undefined
    at Object.SocialCalc.GetStyleNum (evalmachine.<anonymous>:4155:13)
    at SocialCalc.Sheet.GetStyleNum (evalmachine.<anonymous>:1243:84)
    at Object.SocialCalc.ExecuteSheetCommand (evalmachine.<anonymous>:3192:49)
    at Object.SocialCalc.SheetCommandsTimerRoutine (evalmachine.<anonymous>:2578:30)
    at evalmachine.<anonymous>:2565:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
gazeto@praseodym ~ $

```

Lets make it specific:
I want to set up a very simple document, hosting 7 sheets. The **only fancy thing** is:  Cross-sheet references. Between all of them.
The problem: I _never_  get to finish the ethercalc because once I inserted a small number of cross sheet references (ca. 6 or more)  _node_ rockets cpu usage to 100%, calculating the sheets forever. 

You can try yourself by calling https://ethercalc.org/frisbee -> The sheets will never resolve. I pasted the Social Calc Code of each sheet in column D here:  https://ethercalc.org/=frisbee

Hope you can help!

**Comment by eddyparkinson** [comment]
I did change this code, maybe it fixes this. Can you check the lastest version.

From commit:

    fix SheetCache cycle problem - when using several sheets

```
           ss.context.sheetobj.ScheduleSheetCommands "recalc\n", false, true
       | \recalc
         if @data.force
-          SocialCalc.Formula.SheetCache.sheets = {}
+          # only remove updated sheet - fix cycle problem when using many sheets
+          delete SocialCalc.Formula.SheetCache.sheets[@data.room]
           ss?sheet.recalconce = true
         parts = ss.DecodeSpreadsheetSave @data.snapshot if @data.snapshot
         if parts?sheet

```

**Comment by shahn** [comment]
I do not believe this issue is fixed. I installed the latest version using npm, applied the diff you're suggesting above, yet ethercalc quickly exits with a "Killed" message (from the operating system's OOM killer) when trying to load a sheet with references between sheets. I only have two worksheets in this setup.

**Comment by eddyparkinson** [comment]
@shahn I can run 5 sheets with references between sheets without any problems. Suggests your setup is different.

**Comment by eddyparkinson** [comment]
@shahn 

**Your example works**
your example  https://ethercalc.org/frisbee

works: http://sheet.cellmaster.com.au/=frisbee 

**Close**
am closing the issue - But please reopen if you find this has not been fixed. 

the fix was in this pull, 
https://github.com/audreyt/ethercalc/pull/410
 versions dated after  Jul 22 2016 should work

**Comment by kousu** [comment]
Sorry to bump, but nothing is coming up online about this: does ethercalc still support multiple worksheets on a single spreadsheet? I can't figure out how to make a new worksheet with the install at ethercalc.org. Is there a plugin I need to install to make it happen?

**Comment by kousu** [comment]
I did my own hunting: yes multi-sheet support works and was a very large project per https://github.com/audreyt/ethercalc/issues/138, but it was enabled with an (undocumented?) feature flag of prepending the sheet ID by "=".

**Comment by eddyparkinson** [comment]
@kousu there is a wiki - contributions greatly appreciated :) - Related: #553  #316 #138
