### ISSUE TITLE
[request] init.d script ? 

### ISSUE THREAD

**Issue by ychaouche** [audreyt/ethercalc#408]
Hello guys,

I'm trying to write an init.d script for ethercalc so that it can be started and stopped as a daemon. It has the benfit of easing interoperability with monitoring tools (like monit for ex.). I didn't succeed in configuring the port number in the init.d script, I'm not even sure if it's the right location to write that configuration parameter (should be read from /etc/ethercalc.conf maybe ?). Anyway, at the end of the day I need to change the default port number from 8000 (already taken) to anything else and this port number needs to be given at the --port parameter of ethercalc, except I don't know how to pass that from the standard start-stop-daemon ?  the manual page says to use --start --exec $daemon then give all the parameters to the daemon after a "--", like this : start-stop-daemon --start (other options) --exec $ethercalc -- --port=8081

Couldn't get that to work.

```
root@audio-mon[10.10.10.82] ~ # /etc/init.d/ethercacl start
ethercalc is not running
options :  --port 8060
root@audio-mon[10.10.10.82] ~ # Please connect to: http://audio-mon:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8000
  at Object.exports._errnoException (util.js:873:11)
  at exports._exceptionWithHostPort (util.js:896:20)
  at Server._listen2 (net.js:1250:14)
  at listen (net.js:1286:10)
  at net.js:1395:9
  at nextTickCallbackWith3Args (node.js:453:9)
  at process._tickCallback (node.js:359:17)
  at Function.Module.runMain (module.js:443:11)
  at startup (node.js:139:18)
  at node.js:968:3


root@audio-mon[10.10.10.82] ~ # 
```

init.d script
```

#! /bin/bash
### BEGIN INIT INFO
# Provides:          ethercalc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script pour le lancement d'Ethercalc
# Description:       Script pour le lancement d'Ethercalc
### END INIT INFO

# Auteur: Yassine Chaouche <a.chaouche@algerian-radio.dz>
PORT=8060
NAME=ethercalc
DAEMON="/root/DOWNLOADS/node-v4.4.7-linux-x64/bin/node_modules/ethercalc/bin/ethercalc"
OPTIONS=" --port $PORT"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
VERBOSE="yes"
SCRIPTNAME="/etc/init.d/$NAME"
. /lib/init/vars.sh
. /lib/lsb/init-functions

# Exit if the package is not installed
if [[ ! -x "$DAEMON" ]]; then
    echo "le script $DAEMON n'existe pas ou n'est pas executable"
    exit 0
fi

do_status(){
    start-stop-daemon -T --pidfile "$PIDFILE"
    status="$?"
    if [ "$status" = 0 ]; then 
	echo "$NAME" is running with pid $(cat "$PIDFILE")
	return 1
    else
	echo "$NAME" is not running 
	return 0;
    fi
}

do_start(){
  do_status
  status="$?"
  if [ "$status" = 1 ]; then
      echo "$NAME" already running.
      return 1
  else
      echo "options : $OPTIONS"
      start-stop-daemon --start --no-close -b -m --pidfile "$PIDFILE" --exec "$DAEMON" -- "$OPTIONS" || return 1 
  fi
}

do_stop(){  
  start-stop-daemon --stop --retry=TERM/30/KILL/5 --pidfile "$PIDFILE"
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  rm -f $PIDFILE 2>/dev/null
  return "$RETVAL"
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $NAME"
        do_start
        case "$?" in
                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                1|2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $NAME"
        do_stop
	ret="$?"
        case "$ret" in
                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                1|2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;

  status)
	do_status
        ;;

  restart)
	do_stop
	sleep 2
	do_start
	;;
  *)
	
        echo "Mauvais argument. $SCRIPTNAME {start|stop|status|restart}" >&2
        exit 3
        ;;
esac

```

Thanks for any help

**Comment by ychaouche** [comment]
Solved : for some reasons it works best with --port=8060 instead of --port 8060, when invoked from the init.d script.
