### ISSUE TITLE
Runtime errors after upgrading zappa to 5.x due to breaking changes

### ISSUE THREAD

**Issue by atifaziz** [audreyt/ethercalc#422]
#421 breaks at runtime on [`main.ls` line 2](https://github.com/audreyt/ethercalc/blob/1158753a7f4ff4b9172d06cb2f2e203071b5bafb/src/main.ls#L2) with the following error:

```
a:\EtherCalc\node_modules\zappajs\node_modules\express\lib\application.js:123
      throw new Error('\'app.router\' is deprecated!\nPlease see the 3.x to 4.
            ^
Error: 'app.router' is deprecated!
Please see the 3.x to 4.x migration guide for details on how to update your app.
  at EventEmitter.app.defaultConfiguration.Object.defineProperty.get (a:\EtherCalc\node_modules\zappajs\node_modules\express\lib\application.js:123:13)
  at Object.include (a:\EtherCalc\main.js:6:30)
  at Object.zappa.app.context.include (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:409:26)
  at Object.<anonymous> (a:\EtherCalc\app.js:64:17)
  at Object.zappa.app (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:774:10)
  at zappa.run (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:876:18)
  at Object.<anonymous> (a:\EtherCalc\app.js:55:21)
  at Object.<anonymous> (a:\EtherCalc\app.js:66:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at [object Object].Module.runMain [as _onTimeout] (module.js:501:10)
```

Looks like zappajs 0.5.x depended on Express 3.x whereas zappzjs 5.x depends on Express 4.x. As pointed out in the error message, there is a [migration guide for Express to go from 3.x to 4.x](https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x).

**Comment by audreyt** [comment]
Please follow through with the unbreaking then :-) I'm flying to New Zealand tomorrow and will be mostly AFK.

**Comment by atifaziz** [comment]
Use of JSON middleware also breaks at [`main.ls` line 2](https://github.com/audreyt/ethercalc/blob/1158753a7f4ff4b9172d06cb2f2e203071b5bafb/src/main.ls#L2):

```
a:\EtherCalc\node_modules\zappajs\node_modules\express\lib\express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundle
            ^
Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
  at Function.forEach.Object.defineProperty.get (a:\EtherCalc\node_modules\zappajs\node_modules\express\lib\express.js:99:13)
  at zappa.app.context.use.use (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:376:34)
  at Object.zappa.app.context.use (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:389:13)
  at Object.include (a:\EtherCalc\main.js:8:10)
  at Object.zappa.app.context.include (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:409:26)
  at Object.<anonymous> (a:\EtherCalc\app.js:64:17)
  at Object.zappa.app (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:774:10)
```

Needs to be fixed by instead using [`bodyParser.json`](https://github.com/expressjs/body-parser/tree/1.15.2#bodyparserjsonoptions) from [body-parser](https://www.npmjs.com/package/body-parser):

```ls
  @use require \body-parser .json!
```

**Comment by atifaziz** [comment]
Uses of `@client` like on [line 1 of `player.ls`](https://github.com/audreyt/ethercalc/blob/1158753a7f4ff4b9172d06cb2f2e203071b5bafb/src/player.ls#L1) breaks with the error:

```
  at Object.include (a:\EtherCalc\main.js:13:10)
  at Object.zappa.app.context.include (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:409:26)
  at Object.<anonymous> (a:\EtherCalc\app.js:64:17)
  at Object.zappa.app (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:774:10)
  at zappa.run (a:\EtherCalc\node_modules\zappajs\lib\zappa.js:876:18)
  at Object.<anonymous> (a:\EtherCalc\app.js:55:21)
  at Object.<anonymous> (a:\EtherCalc\app.js:66:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at [object Object].Module.runMain [as _onTimeout] (module.js:501:10)
  at Timer.listOnTimeout (timers.js:110:15)
```

[ZappaJS changed this with 4.0](https://github.com/zappajs/zappajs#embedded-client-side-code):

> The ZappaJS client is no longer embedded and was moved to a separate module, [zappajs-client](https://www.npmjs.com/package/zappajs-client).

**Comment by atifaziz** [comment]
@audreyt Given the number of breaking changes (so far), we might have moved too fast on #420 and it may be best to revert 141fa2d1748961eebd76b633a03455796182f977? I think this should be worked out on a separate branch/PR instead of having the `master` broken, especially since [you're going to be AFK](https://github.com/audreyt/ethercalc/issues/422#issuecomment-240714057)? Thoughts?

**Comment by audreyt** [comment]
Sure, reverted, please feel free to branch/fork and work.

**Comment by eddyparkinson** [comment]
@atifaziz I also hit too many breaking changes. I have been adding http2 style server push #373, but hit more errors after fixing @client. 

this fixes the error:
@include = -> 
  @with 'client' 
  @client '/player/broadcast.js': ->

but the fix dumps over 1MB of javascript into the file, also more errors are reported by the browser.

Server push example: https://github.com/zappajs/zappajs/blob/6.x/examples/spdy.coffee

@shimaore

**Comment by shimaore** [comment]
@eddyparkinson @atifaziz do you have a dev branch with recent zappajs that I could look at to help?

Also I'm not sure using `@client` is required in [player-broadcast.ls](https://github.com/audreyt/ethercalc/blob/master/src/player-broadcast.ls) since it seems to be using `window.` for globals — have you tried using `@js` directly instead of `@client`?

**Comment by eddyparkinson** [comment]
**Upgrade guide?**
 @shimaore I see a list of changes to zappa here https://github.com/zappajs/zappajs 
 do you have an upgrade guide, as it would be handy.

**http2push dev branch**
https://github.com/eddyparkinson/cellmaster/tree/http2push

*zappa files in src/*
 I suspect only files in srcr use zappa, but am not 100% sure.

**Comment by shimaore** [comment]
I've started a [zappa6 branch](https://github.com/shimaore/ethercalc/tree/zappa6) to adapt for recent ZappaJS. I've [updated](https://github.com/shimaore/ethercalc/commit/c489c1b339cf0debc4560cb8eec40ce4089c7234) most things related to loading content. I still have to look at how ethercalc handles Redis (in `src/db.ls`), though.

**Comment by eddyparkinson** [comment]
@shimaore errors:

- static folder is no longer serving content.  

looks like main.ls (line 5) needs

@include = ->
  @use bodyParser.json(), serveStatic __dirname

- SocialCalc.Callbacks.broadcast is not a function(…)  
in main.js

**Comment by shimaore** [comment]
@eddyparkinson 

> 1) static folder is no longer serving content.
>   @use serveStatic __dirname

Indeed [It is there](https://github.com/shimaore/ethercalc/blob/c489c1b339cf0debc4560cb8eec40ce4089c7234/src/main.ls#L538) :sunny: → what specific content do you see not loading?

Regarding the other issues I need to put some time aside to finish this; once I have something working I'll send a PR over for review.

**Comment by eddyparkinson** [comment]
Sorry about error 1, my mistake. Yes that works.

Error 2 & 3, looking forward to the PR


 looks

**Comment by eddyparkinson** [comment]
@shimaore any thoughts on errors 2 & 3 above?
