### ISSUE TITLE
ethercalc syntax error

### ISSUE THREAD

**Issue by chazdiezal** [audreyt/ethercalc#492]
When running 'ethercalc' i get the error below, any ideas?

/usr/local/lib/node_modules/ethercalc/node_modules/nodemailer/lib/nodemailer.js:3
const Mailer = require('./mailer');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.include (/usr/local/lib/node_modules/ethercalc/emailer.js:13:18)
    at Object.context.include (/usr/local/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.include (/usr/local/lib/node_modules/ethercalc/sc.js:214:20)
    at Object.context.include (/usr/local/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.include (/usr/local/lib/node_modules/ethercalc/main.js:17:15)
    at Object.context.include (/usr/local/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethercalc/app.js:58:17)
    at Object.zappa.app (/usr/local/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:875:10)
    at zappa.run (/usr/local/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:1024:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethercalc/app.js:49:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethercalc/app.js:60:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethercalc/bin/ethercalc:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by eddyparkinson** [comment]
Change the nodemailer version 

This line:
https://github.com/audreyt/ethercalc/blob/master/package.json#L17

change
    "nodemailer": "*",
to
    "nodemailer": "3.0.2",

as I have 3.0.2 installed - and it works ok.

Pull requests welcome.

**Bug?**
Looks like they changed it 2 days ago, v3.1.3, suspect it caused this. 
https://github.com/nodemailer/nodemailer/commit/ef202df0fcdd3b12736e4200cc18394f05eb07d0


As you can see, a few changes this week:
https://github.com/nodemailer/nodemailer/releases
2 days ago 
v3.1.3  …
 ef202df   zip   tar.gz
3 days ago 
v3.1.2  …
 0097988   zip   tar.gz
5 days ago 
v3.1.1  …
 315eb22   zip   tar.gz
6 days ago 
v3.1.0  …
 689f834   zip   tar.gz
16 days ago 
v3.0.2  …
 9408e5f   zip   tar.gz
16 days ago 
v3.0.1  …
 c17d643   zip   tar.gz
20 days ago 
v3.0.0  …
 eaef3b5   zip   tar.gz

**Comment by eddyparkinson** [comment]
Nodemailer v3+ requires at least Node.js v6.0.0. To support older versions of Node.js you should downgrade Nodemailer to v2.7.2

**Comment by chazdiezal** [comment]
Thanks eddy, this solved my issue.

**Comment by goiken** [comment]
I get the same bug. I’ve no idea what my version of nodemailer is. I tried `npm ls nodemailer` and got

`ethercalc@0.20170303.0 /home/mtb/node_modules/ethercalc
└── nodemailer@4.0.0`

But setting ` "nodemailer": "*",` to ` "nodemailer": "4.0.0",` didn’t fix this for me.

**Comment by eddyparkinson** [comment]
@goiken what version of node are you using? If it is old,before v6.0.0, then try setting "nodemailer": "2.7.2"

**Comment by goiken** [comment]
´$ node --version´
´v0.10.43´

Setting it to `"nodemailer": "2.7.2",` didn’t work… But I upgraded to `v7.5.0` and it worked. Thx.
