### ISSUE TITLE
ethercalc not launching in ubuntu instances of Docker and c9.io

### ISSUE THREAD

**Issue by 36thNinja** [audreyt/ethercalc#523]
Whenever i am trying to launch ethercalc using docker or c9.io(ubuntu instance). It is not working and throwing an error as shown below. But it is running locally without any issues in Mac.

````
a36thninja:/ $ ethercalc
Please connect to: http://a36thninja-ether-4985966:8080/
Starting backend using webworker-threads
/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.__dirname.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/emailer.js:13:18)
    at Object.context.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.__dirname.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/sc.js:214:20)
    at Object.context.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.__dirname.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/main.js:17:15)
    at Object.context.include (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/app.js:58:17)
    at Object.zappa.app (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:875:10)
    at zappa.run (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:1024:18)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/app.js:49:21)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/app.js:60:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/ethercalc/bin/ethercalc:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3`
```

Is it some thing related to port binding or IP binding in those platforms or anything related to dependencies?

**Comment by eddyparkinson** [comment]
To start the service try
` node app.js
`

Am guessing ... it looks like livescript.  It looks like is is tring to re-compile the src/*.ls files.
This is not needed, unless you need to change the source.

It does require livescript to recompile. See the Make file.

**Comment by SebiWolze** [comment]
Got the same error whenever i try to start the service.
What can i do? I am not a developer.

**Comment by eddyparkinson** [comment]
Looks like an old version of node

andris9 wrote:

>Nodemailer v3+ requires at least Node.js v6.0.0. To support older versions of Node.js you should >downgrade Nodemailer to v2.7.2 

from:
https://github.com/audreyt/ethercalc/issues/492

**Comment by Strubbl** [comment]
Current docker build is affected by this issue. To reproduce checkout this repo, docker build and run. 
Is docker hub image not affected because it was built 5 months ago?

**Comment by eddyparkinson** [comment]
@Strubbl @audreyt  Re:"docker build" problem.  Do you know someone who can help? I have never configured docker, I know little about it.

**Comment by Strubbl** [comment]
@eddyparkinson it looks like it is a dependency problem with node 4.4 and nodemailer. 

In what environment are you running ethercalc master branch currently?

**Comment by eddyparkinson** [comment]
I know of about 5 groups that run public servers. No idea what version of node they use. But
yes I think the latest version of nodemailer requires a newish version of node.

andris9 wrote:

> Nodemailer v3+ requires at least Node.js v6.0.0. To support older versions of Node.js you should downgrade Nodemailer to v2.7.2
