### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Pofilo** [audreyt/ethercalc#543]
I'm doing the installation as it is explained in the `README`:
```
npm i -g ethercalc
ethercalc
```

However, when I run the command `ethercalc`, I get this error:
```
Starting backend using webworker-threads
/usr/lib/node_modules/ethercalc/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.__dirname.include (/usr/lib/node_modules/ethercalc/emailer.js:13:18)
    at Object.context.include (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.__dirname.include (/usr/lib/node_modules/ethercalc/sc.js:214:20)
    at Object.context.include (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.__dirname.include (/usr/lib/node_modules/ethercalc/main.js:17:15)
    at Object.context.include (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:58:17)
    at Object.zappa.app (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:875:10)
    at zappa.run (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:1024:18)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:49:21)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:60:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/bin/ethercalc:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

Versions used:

- Ubuntu 16.04
- npm: 2.15.11
- node: v4.8.4
- redis: v=3.0.6

Do you have an idea why I get this ?
Thanks.

**Comment by eddyparkinson** [comment]
#523 

The latest version of nodemailer requires a newish version of node.

andris9 wrote:

>Nodemailer v3+ requires at least Node.js v6.0.0. To support older versions of Node.js you should >downgrade Nodemailer to v2.7.2

@Pofilo let me know if this works and I will update the readme

**Comment by Pofilo** [comment]
Downgrading nodemailer to v2.7.2 is the solution.

Thanks for your answer and sorry for the duplicate (I was looking for installations' issues and I didn't find any).

Yes, you can update the readme !
