### ISSUE TITLE
High memory usage issue

### ISSUE THREAD

**Issue by amir-zeldes** [audreyt/ethercalc#554]
Hi,

I'm encountering high memory usage by the node process when ethercalc hasn't been restarted for several weeks. It goes up to about 11GB and seems to stay there, then restarting the service gets everything back down to a fraction of that. I realize this is a rather vague bug report (if it's a bug), but I would appreciate any guidance you might have in diagnosing the cause of this. Maybe some kind of memory leak?

Additional info:
  * I'm running node v0.10.46
  *  ethercalc@0.20161029.0
  * System is Red Hat Enterprise Linux Server release 6.9 (Santiago)
  * EtherCalc has about 300 rooms stored, using redis
  * I often have about 25 concurrent users, typically one or two working on the same spreadsheet

**Comment by amir-zeldes** [comment]
Update: About 24 hours after restart, memory usage is at about 3GB, seems to be rising slowly but steadily. I found this article about garbage collection in node js:

https://blog.risingstack.com/finding-a-memory-leak-in-node-js/

I could not find an entry point running server.js in the EtherCalc code as suggested in that post, so I naively tried adding the option `--max_old_space_size` to the shebang in /usr/bin/ethercalc like this:

```
#!/usr/bin/env node --max_old_space_size=1000

var path = require("path");
...
```

But this causes EtherCalc not to start, so that's a dead end for now. Any ideas or things to check are appreciated!

**Comment by eddyparkinson** [comment]
I agree with this.  I restart the server every 24 hours, because it tends to crash when I open a new sheet after it has been running for a few days. 

Detect memory leak node js
---
I don't know what the best tool are, but a quick google search brings up some options
https://www.google.com.au/search?q=detect+memory+leak+node+js

**Comment by amir-zeldes** [comment]
I had a look - this is a little over my head TBH - I have never developed for node.js and I'm not really familiar with the inner workings of Ether/SocialCalc. Is there any chance someone more familiar with the project could have a look? Is this affecting all users or just some, and if so, is everyone just auto-restarting daily or what is the best way to handle this?

Thanks for your help as always!

**Comment by eddyparkinson** [comment]
>auto-restarting daily

This works for me. Suggest you try this and report back.

**Comment by poVoq** [comment]
Maybe somewhat related, but why doesn't Ethercalc go back to base level RAM use when not in use?
A freshly started Ethercalc service uses around 80mb RAM when started. Then if some users connect and use it, it goes up varying levels, but usually around 250mb in my tests.
However that figure doesn't go back down again to 80mb or so when all clients close their browser windows, not even after considerable amount of time. The only way to get RAM user back down it to restart the service.

**Comment by eddyparkinson** [comment]
@poVoq Happy for you to have a go at fixing. Do we know what would fix the problem? Re-starting ethercalc looks to work. But I don't know what else would work.

**Comment by eddyparkinson** [comment]
Crash
---

Crash caused by zappajs@0.5.0 - because it uses ws@0.4.31 

Fix: restarting every 24 hours looks to fix this, but ideal would be to upgrade zappajs.

Error details:
--------
node_modules\engine.io\node_modules\ws\lib\Receiver.js:323
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^
RangeError: out of range index
  at RangeError (native)
  at fastCopy (C:\cygwin64\home\eddy\cellmaster\node_modules\engine.io\node_modules\ws\lib\Receiver.js:323:24)
  at Receiver.add (C:\cygwin64\home\eddy\cellmaster\node_modules\engine.io\node_modules\ws\lib\Receiver.js:84:3)
  at Socket.firstHandler (C:\cygwin64\home\eddy\cellmaster\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:678:22)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:548:20)

https://github.com/websockets/ws/issues/778

**Comment by amir-zeldes** [comment]
Fantastic, I also haven't tested rigorously, but I used to be able to see memory rising constantly, and after this it's just standing still. 

The only thing I noticed is that opening lots of live EtherCalc spreadsheet clients raises the memory usage (as expected), but closing those browser windows does not bring memory back down. It stays at the maximum it reached after opening n connections. So maybe restarting it periodically is still not a bad idea, but at least there's no ballooning memory leak anymore. Thanks a lot!!

**Comment by andreasmerkel** [comment]
Hi,
we have the same issues at our company. We have many people who use ethercalc with browsers and/or curl for their workflows. Especially, when using curl to put a large csv file to ethercalc, you can watch memory growing until the service stops with following error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x10a0dcc [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x156ba83079a7
Aborted
```
Restarting the service is a workaround, but our server with 8GB RAM doesn't work for 24 hours with this memory leak.
BTW: I tested the setup with Node.js v4, v6 and v8 with the same results. Also, updating to ws@1.1.1 doesn't fix the problem.

**Comment by eddyparkinson** [comment]
@andreasmerkel  the out of memory issue would need a code change. The problem is sheets are never removed from memory.  It works by loading each sheet into memory on the server and never removing it. The way round would be to track active sheets, and remove any non-active sheets from server memory. 

Also it would be worth profiling ethercalc to see if there are any memory leaks and fix them. That said, most of the code is production quality, I have not seen any memory leaks in the code I have edited.

**Comment by andreasmerkel** [comment]
I think, the memory consumption by loading each used sheet into the server memory is not our problem (although it would be nice to have a garbage collection).
Our "memory leak" is easily reproducible. We used a fresh debian stretch installation with the ethercalc docker image and uploaded a sheet. Now use curl to get this sheet many times. Every time you curl the sheet, the memory consumption raises by 10-100MB (until the server crashes as described above).
