### ISSUE TITLE
cant connect to redis using socket

### ISSUE THREAD

**Issue by jonazc** [audreyt/ethercalc#570]
I try connecting via unix socket to redis, but out of any reasons it doesn't work. I use:

```
export REDIS_SOCKPATH="redis-cli -s ~/.redis/sock"
/package/host/localhost/nodejs-6/bin/node /home/user/src/ethercalc/app.js --host localhost --port 63550 2>&1
```

but that results in the error

```
Please connect to: http://localhost:65000/
Starting backend using webworker-threads
Error: Redis connection to redis-cli -s ~/.redis/sock failed - connect ENOENT redis-cli -s ~/.redis/sock
    at RedisClient.on_error (/home/user/src/ethercalc/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/home/user/src/ethercalc/node_modules/redis/index.js:106:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

==> Falling back to JSON storage: /home/user/src/ethercalc/dump.json
Express server listening on port 65000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
```

**Comment by eddyparkinson** [comment]
Did you fix it? REDIS_SOCKPATH implies host:port - e.g.  server.cloud.com:6000 

Your "redis-cli" looks wrong, as this for using from the command line, not via a socket.

**Comment by audreyt** [comment]
The TypeScript rewrite on Cloudflare Workers (`sandstorm` branch) replaces Redis with Durable Object storage + D1 mirror (see [CLAUDE.md §3](https://github.com/audreyt/ethercalc/blob/sandstorm/CLAUDE.md) / §10.2). Redis-specific config, sockets, backup, and cluster concerns no longer apply. Closing; please re-open if you hit an analogous issue on the new stack.
