### ISSUE TITLE
Multiple sheets export crashes

### ISSUE THREAD

**Issue by mathiasblc** [audreyt/ethercalc#573]
Hello,

When I create a calc with more sheets than one and try to export it, it crash everytime.

For information we are running v0.20170704.0, and here is some logs:
```/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:602
throw err;
^

Error: Duplicate Sheet Name: Sheet2
at /var/www/ethercalc-preprod/ethercalc/node_modules/j/node_modules/xlsx/xlsx.js:11600:50
at Array.forEach (<anonymous>:null:null)
at check_wb_names (/var/www/ethercalc-preprod/ethercalc/node_modules/j/node_modules/xlsx/xlsx.js:11597:4)
at check_wb (/var/www/ethercalc-preprod/ethercalc/node_modules/j/node_modules/xlsx/xlsx.js:11605:2)
at Object.writeSync [as write] (/var/www/ethercalc-preprod/ethercalc/node_modules/j/node_modules/xlsx/xlsx.js:16691:2)
at Object.to_ods (/var/www/ethercalc-preprod/ethercalc/node_modules/j/j.js:217:15)
at Array.<anonymous> (/var/www/ethercalc-preprod/ethercalc/main.js:282:35)
at /var/www/ethercalc-preprod/ethercalc/main.js:189:39
at /var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:1170:13
at try_callback (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:592:9)
at RedisClient.return_reply (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:685:13)
at ReplyParser.<anonymous> (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:321:14)
at emitOne (events.js:116:13)
at ReplyParser.emit (events.js:211:7)
at ReplyParser.send_reply (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/lib/parser/javascript.js:300:10)
at ReplyParser.execute (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/lib/parser/javascript.js:211:22)
at RedisClient.on_data (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:547:27)
at Socket.<anonymous> (/var/www/ethercalc-preprod/ethercalc/node_modules/redis/index.js:102:14)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:594:20)
```

Thanks in advance for your help.
Regards,

**Comment by eddyparkinson** [comment]
Muti-sheet export - version issue?
---
Looks like a version issue. Because this works: 
 https://ethercalc.org/=example_mutisheet 

What version of j/xlsx.js are you using? https://github.com/audreyt/ethercalc/blob/master/package.json#L14
Is your version of xlsx.js up to date? As it was updated several months ago. 
 

I don't know if a bug was introduced or if you are missing an update. Let me know what you discover and I will try to help pin it down.

**Comment by poVoq** [comment]
For me it works to export to Excel (just freshly installed ethercalc), but the renaming of sheets gets picked up inconsistently... most of the time the exported sheets stay named "Sheet1" etc as the default, but not always. It's a bit odd.

**Comment by audreyt** [comment]
Resolved by ecb18d3: multi-sheet export routes (`GET /_/=:room/xlsx|ods|fods`) now walk the TOC row-by-row, fetch each sub-room's sheet-data via `/_do/sheet-data`, and assemble one workbook with formula fidelity per sub-sheet. No more crash.
