### ISSUE TITLE
Crash on ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by elacour** [audreyt/ethercalc#588]
We have a calc that makes ethercalc crash and restart ina loop, with the following error:

evalmachine.<anonymous>:6806
      value = ((navigator.language).indexOf("fr") === 0)  ? (SocialCalc.FormatNumber.convert_date_gregorian_to_julian(year, matches[2]-0, matches[1]-0)-2415019) : (SocialCalc.FormatNumber.convert_date_gregorian_to_julian(year, matches[1]-0, matches[2]-0)-2415019);
      ^

ReferenceError: navigator is not defined
    at Object.SocialCalc.DetermineValueType (evalmachine.<anonymous>:6806:7)
    at SocialCalc.Formula.OperandAsNumber (evalmachine.<anonymous>:16091:62)
    at Object.SocialCalc.Formula.EvaluatePolish (evalmachine.<anonymous>:15863:24)
    at Object.SocialCalc.Formula.evaluate_parsed_formula (evalmachine.<anonymous>:15518:17)
    at SocialCalc.RecalcTimerRoutine (evalmachine.<anonymous>:4750:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by elacour** [comment]
This is ethercalc master @95802205fed8fddd902c1e225f92b3a689071bb9

**Comment by eddyparkinson** [comment]
Looks like this line

https://github.com/marcelklehr/socialcalc/blob/master/js/socialcalc-3.js#L5951

Is the error in the browser or the server?

Might be browser related as  "navigator.language which works in IE11+ ... use navigator.userLanguage for compat with old IEs"  See https://stackoverflow.com/questions/2678230/how-to-getting-browser-current-locale-preference-using-javascript

**Comment by elacour** [comment]
I'm very too bad in JS to propose a correct patch. Here I just added a test:

value = (typeof navigator !== 'undefined' && typeof navigator.language !== 'undefined' && (navigator.language).indexOf("fr") === 0) ...

it fixes the crash and UI looks ok.

Seems this bug should be targeted to SocialCalc instead ?
