### ISSUE TITLE
install not successfull (debian)

### ISSUE THREAD

**Issue by c-ascha** [audreyt/ethercalc#591]
Hello,
could you help me with the installation?
something must be wrong..

Log:
ethercalc@&host:~$ ethercalc 
Please connect to: http://$host:8000/
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/ethercalc/node_modules/socialcalc/dist/SocialCalc.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:108:72)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/sc.js:7:15)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/sc.js:809:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.context.include (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:580:37)
    at Object.__dirname.include (/usr/lib/node_modules/ethercalc/main.js:17:15)
    at Object.context.include (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:58:17)
    at Object.zappa.app (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:875:10)
    at zappa.run (/usr/lib/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:1024:18)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:49:21)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/app.js:60:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/ethercalc/bin/ethercalc:7:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

ethercalc@$host:~$

Thank you
c_ascha

**Comment by c-ascha** [comment]
Fixed, just copied one file in a new folder:
