### ISSUE TITLE
use docker-compose.yml to deploy ethercalc would cause error  redis can not connet

### ISSUE THREAD

**Issue by curexiaoxiao** [audreyt/ethercalc#595]
**Environment** :  
       system: centos7   
       docker: 17.12.0-ce    
       docker-compose: 1.19.0

**Detail**:
        use docker-compose.yml  to deploy ethercalc would cause an error, redis can not connet. error     
   log like that :
```
es_ethercalc | 0|ethercal | Error: Redis connection to  failed - connect ECONNREFUSED 127.0.0.1
es_ethercalc | 0|ethercal |     at RedisClient.on_error (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:196:24)
es_ethercalc | 0|ethercal |     at Socket.<anonymous> (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:106:14)
es_ethercalc | 0|ethercal |     at emitOne (events.js:96:13)
es_ethercalc | 0|ethercal |     at Socket.emit (events.js:191:7)
es_ethercalc | 0|ethercal |     at emitErrorNT (net.js:1283:8)
es_ethercalc | 0|ethercal |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
es_ethercalc | 0|ethercal |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
es_ethercalc | 0|ethercal | ==> Falling back to JSON storage: //dump.json

```

**Comment by curexiaoxiao** [comment]
i create a patch to fix this error https://github.com/audreyt/ethercalc/pull/596

**Comment by eddyparkinson** [comment]
Please add a testing summary. Something to indicate every change was tested.

**Comment by audreyt** [comment]
The TypeScript rewrite on Cloudflare Workers (`sandstorm` branch) replaces Redis with Durable Object storage + D1 mirror (see [CLAUDE.md §3](https://github.com/audreyt/ethercalc/blob/sandstorm/CLAUDE.md) / §10.2). Redis-specific config, sockets, backup, and cluster concerns no longer apply. Closing; please re-open if you hit an analogous issue on the new stack.
