### ISSUE TITLE
Currently can't build

### ISSUE THREAD

**Issue by axtens** [audreyt/ethercalc#664]
```
CMD>git clone https://github.com/audreyt/ethercalc.git
Cloning into 'ethercalc'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 7476 (delta 4), reused 6 (delta 4), pack-reused 7462
Receiving objects: 100% (7476/7476), 12.22 MiB | 2.35 MiB/s, done.
Resolving deltas: 100% (4329/4329), done.

CMD>cd ethercalc

CMD\ethercalc>dir
 Volume in drive C is OS
 Volume Serial Number is 2652-D365

 Directory of CMD\ethercalc

04/05/2019  03:49 PM    <DIR>          .
04/05/2019  03:49 PM    <DIR>          ..
04/05/2019  03:49 PM    <DIR>          .dotcloud
04/05/2019  03:49 PM                28 .gitignore
04/05/2019  03:49 PM    <DIR>          .openshift
04/05/2019  03:49 PM             1,468 android-chrome-192x192.png
04/05/2019  03:49 PM    <DIR>          apache
04/05/2019  03:49 PM             4,381 API.md
04/05/2019  03:49 PM    <DIR>          app-graphics
04/05/2019  03:49 PM             1,935 app.js
04/05/2019  03:49 PM             1,047 apple-touch-icon.png
04/05/2019  03:49 PM    <DIR>          bin
04/05/2019  03:49 PM               285 browserconfig.xml
04/05/2019  03:49 PM            24,494 Changes.txt
04/05/2019  03:49 PM            10,638 db.js
04/05/2019  03:49 PM               320 docker-compose.yml
04/05/2019  03:49 PM               349 Dockerfile
04/05/2019  03:49 PM               789 dotcloud.js
04/05/2019  03:49 PM                88 dotcloud.yml
04/05/2019  03:49 PM             1,701 emailer.js
04/05/2019  03:49 PM               961 exports.js
04/05/2019  03:49 PM               360 favicon-16x16.png
04/05/2019  03:49 PM               432 favicon-32x32.png
04/05/2019  03:49 PM            15,086 favicon.ico
04/05/2019  03:49 PM    <DIR>          images
04/05/2019  03:49 PM             3,642 index.html
04/05/2019  03:49 PM    <DIR>          l10n
04/05/2019  03:49 PM            50,391 LICENSE.txt
04/05/2019  03:49 PM            38,978 main.js
04/05/2019  03:49 PM             2,198 Makefile
04/05/2019  03:49 PM             2,160 manifest.appcache
04/05/2019  03:49 PM               191 manifest.json
04/05/2019  03:49 PM    <DIR>          misc
04/05/2019  03:49 PM             1,082 mstile-150x150.png
04/05/2019  03:49 PM             2,797 mstile-310x310.png
04/05/2019  03:49 PM    <DIR>          multi
04/05/2019  03:49 PM    <DIR>          nginx
04/05/2019  03:49 PM           152,253 package-lock.json
04/05/2019  03:49 PM             1,109 package.json
04/05/2019  03:49 PM             2,729 panels.html
04/05/2019  03:49 PM             6,395 player-broadcast.js
04/05/2019  03:49 PM            44,007 player-graph.js
04/05/2019  03:49 PM            26,944 player.js
04/05/2019  03:49 PM            86,872 privacy.png
04/05/2019  03:49 PM             5,281 README.mkdn
04/05/2019  03:49 PM                 6 requirements.txt
04/05/2019  03:49 PM                26 robots.txt
04/05/2019  03:49 PM               993 safari-pinned-tab.svg
04/05/2019  03:49 PM            29,472 sc.js
04/05/2019  03:49 PM                 6 server.js
04/05/2019  03:49 PM               585 snapcraft.yaml
04/05/2019  03:49 PM    <DIR>          src
04/05/2019  03:49 PM               101 stackato.yml
04/05/2019  03:49 PM            11,595 start.html
04/05/2019  03:49 PM    <DIR>          static
04/05/2019  03:49 PM                72 supervisord.conf
04/05/2019  03:49 PM    <DIR>          third-party
04/05/2019  03:49 PM               478 webpack.config.js
04/05/2019  03:49 PM            97,799 yarn.lock
04/05/2019  03:49 PM                10 _start
              45 File(s)        632,534 bytes
              15 Dir(s)  148,893,331,456 bytes free

CMD\ethercalc>npm i

> ws@0.4.31 install CMD\ethercalc\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


CMD\ethercalc\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> webworker-threads@0.7.16 install CMD\ethercalc\node_modules\webworker-threads
> node-gyp rebuild


CMD\ethercalc\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\bugma\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd CMD\ethercalc\node_modules\webworker-threads
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ethercalc@0.20180825.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.16 (node_modules\webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.16 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 495 packages from 442 contributors and audited 1084 packages in 15.844s
found 77 vulnerabilities (31 low, 25 moderate, 20 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

CMD\ethercalc>npm audit fix

> webworker-threads@0.7.16 install CMD\ethercalc\node_modules\webworker-threads
> node-gyp rebuild


CMD\ethercalc\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\bugma\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd CMD\ethercalc\node_modules\webworker-threads
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ethercalc@0.20180825.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.16 (node_modules\webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.16 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 4.987s
fixed 0 of 77 vulnerabilities in 1081 scanned packages
  1 vulnerability required manual review and could not be updated
  5 package updates for 76 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

**Comment by eddyparkinson** [comment]
Webworkers
---

  It will run without webworkers, webworker is optional., 


make vs node-gyp
---

 I have only used make to compile, never node-gyp. If I remember, someone added node-gyp over 1 year ago, but I did not try it.

Failing
---

>npm i

Is it "npm i" that is failing or node-gyp. Or both, thoughts?

**Comment by audreyt** [comment]
The LiveScript + Makefile + `npm publish` + legacy Dockerfile pipeline is fully replaced in the TypeScript rewrite (Bun + Vite + wrangler, with a Miniflare Docker image for self-host — [CLAUDE.md §9 / §11](https://github.com/audreyt/ethercalc/blob/sandstorm/CLAUDE.md)). Legacy build/install failures no longer apply. Closing.
