### ISSUE TITLE
Cannot make post requests to ethercalc

### ISSUE THREAD

**Issue by KhalfaniW** [audreyt/ethercalc#687]
I just installed ethercalc. I am trying use curl to post to a spreadsheet. 

This example I got from [issue 74](https://github.com/audreyt/ethercalc/issues/74) works

```
$ echo 'one,two,three' | \
    curl -i -H "Content-Type: text/csv" -X POST --data-binary @- \
        https://ethercalc.org/_/test-74
```

When I use my url, it waits for two minutes and times out.
```
$ echo 'one,two,three' | \
    curl -i -H "Content-Type: text/csv" -X POST --data-binary @- \
       http://localhost:8000/_/pxcqc2pxnu2u
```
```
curl: (52) Empty reply from server
```

I checked to make sure ethercalc is running on :8000 

```
$ ethercalc
Please connect to: http://laptop:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

==> Falling back to file system storage: /home/user/dump/
==> Restored previous session from dump storage
join [log-pxcqc2pxnu2u] [user-0.9399518489936889]
```

Every time I try to make a post request as with a csv, ethercalc outputs this error message

```
TypeError: X.utils[("sheet_to_" + t)] is not a function
    at /usr/local/lib/node_modules/ethercalc/node_modules/j/j.js:210:39
    at Array.forEach (<anonymous>:null:null)
    at Object.to_socialcalc (/usr/local/lib/node_modules/ethercalc/node_modules/j/j.js:206:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ethercalc/main.js:484:34)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by KhalfaniWadlington** [comment]
$ node --version
v10.15.2

**Comment by eddyparkinson** [comment]
Create the sheet first
---

curl  -H "Content-Type: application/json" -X POST http://${server}/_ -d '{ "room": " status", "snapshot": ""}'

Do you create the sheet first? From memory, the sheet/room needs to already exist for this to work.

**Comment by KhalfaniWadlington** [comment]
```
$ curl -H "Content-Type: application/json" -X POST http://localhost:8000/rbebq2ks3ntl/_ -d '{ "room": " status", "snapshot": ""}'

Cannot POST /rbebq2ks3ntl/_
```

The sheet exists and is editable. Thats where I got the link

**Comment by eddyparkinson** [comment]
I can't replicate this. Looks to work with my local server and sheet.cellmaster.com.au 

Firewall?

**Comment by KhalfaniWadlington** [comment]
I have no clue. I tried it on my vps that I rent and is live on the internet. Then I killed it and ran ethercalc on port 80. Then I ran it on my home linux computer. I have never had any firewall issues because I have not never installed a firewall on. 


I can make GET requests to ethercalc with curl. I can also make post requests to other services on other ports. 


What does the following output mean when i run `ethercalc`. 
```
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ethercalc/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by eddyparkinson** [comment]
> I can also make post requests to other services on other ports.

Does that mean no POST requests to ethercalc work for you. But GET works fine.

**Comment by KhalfaniWadlington** [comment]
No Post requests work. I even tried to make an `$.ajax` post request .

Even the most basic post request failed
```
$ curl -d "param1=val1&param2=val2" -X POST http://localhost:8000/_/61oxk499cqoj 
curl: (52) Empty reply from server
```

But GET requests work 
```
$ curl -d "param1=val1&param2=val2" -X GET http://localhost:8000/_/61oxk499cqoj 
socialcalc:version:1.0
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=SocialCalcSpreadsheetControlSave
--SocialCalcSpreadsheetControlSave
Content-type: text/plain; charset=UTF-8

# SocialCalc Spreadsheet Control Save
version:1.0
part:sheet
part:edit
part:audit
--SocialCalcSpreadsheetControlSave
Content-type: text/plain; charset=UTF-8

version:1.5
sheet:c:1:r:1:tvf:1
valueformat:1:text-wiki
--SocialCalcSpreadsheetControlSave
Content-type: text/plain; charset=UTF-8

version:1.0
rowpane:0:1:1
colpane:0:1:1
ecell:A1
--SocialCalcSpreadsheetControlSave
Content-type: text/plain; charset=UTF-8

--SocialCalcSpreadsheetControlSave--
```

**Comment by eddyparkinson** [comment]
Can you try another machine or something? Sounds a lot like a firewall issue to me. Maybe setup a simple express web app and try sending a post request?

I assume you are using standard nodejs code and the normal ethercalc code.

**Comment by KhalfaniWadlington** [comment]
I tried it on my vps that I run apps on other ports on. 

Then I tried it on my local linux computer. 
```
$ curl -X POST http://localhost:8000/_/dmz7n2hxanqp

curl: (52) Empty reply from server
```

I set up a express app with the following code
```
var express = require('express');
var app = express();
app.get('/', function (req, res) {
    res.send('<html><body><h1>Hello World</h1></body></html>');
});
app.post('/submit-data', function (req, res) {
    res.send('POST Request recieved');
});
var server = app.listen(8000, function () {
    console.log('Node server is running..');
});
```

And it worked
```
$ curl -X POST http://localhost:8000/submit-data
POST Request recieved
```
