### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mbressman** [audreyt/ethercalc#748]
Am running EtherCalc on Ubuntu 18.04.  All of a sudden it's started crashing a lot.  I have it set to run as a background service, bu when I run it as a command from the shell and then start using it, it crashes with this error:

Segmentation fault (core dumped)

Couldn't find anything else in the list of issues on here about this error - any thoughts or suggestions?  Thanks!

**Comment by mbressman** [comment]
Just tried to launch it again and got this:

Starting backend using webworker-threads
events.js:183
&nbsp;&nbsp;&nbsp;&nbsp;      throw er; // Unhandled 'error' event
&nbsp;&nbsp;&nbsp;&nbsp;      ^

Error: listen EADDRINUSE 0.0.0.0:8000
&nbsp;&nbsp;&nbsp;&nbsp;    at Object._errnoException (util.js:1022:11)
&nbsp;&nbsp;&nbsp;&nbsp;    at _exceptionWithHostPort (util.js:1044:20)
&nbsp;&nbsp;&nbsp;&nbsp;    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
&nbsp;&nbsp;&nbsp;&nbsp;    at listenInCluster (net.js:1408:12)
&nbsp;&nbsp;&nbsp;&nbsp;    at doListen (net.js:1517:7)
&nbsp;&nbsp;&nbsp;&nbsp;    at _combinedTickCallback (internal/process/next_tick.js:141:11)
&nbsp;&nbsp;&nbsp;&nbsp;    at process._tickCallback (internal/process/next_tick.js:180:9)
&nbsp;&nbsp;&nbsp;&nbsp;    at Function.Module.runMain (module.js:695:11)
&nbsp;&nbsp;&nbsp;&nbsp;    at startup (bootstrap_node.js:188:16)
&nbsp;&nbsp;&nbsp;&nbsp;    at bootstrap_node.js:609:3

**Comment by eddyparkinson** [comment]
>Error: listen EADDRINUSE 0.0.0.0:8000

this suggests somethings else is running on port 8000. 
also not sure why the IP number is  0.0.0.0 ... looks odd

**Comment by mbressman** [comment]
Very strange since I don't run anything else really on that virtual server, but maybe somehow I was running EtherCalc as the background process when I launched it again in the shell?

Any thoughts on the "Segmentation fault (core dumped)" error?

Thanks!

**Comment by eddyparkinson** [comment]
Webworkers
---

It will run without webworkers, webworker is optional. I think I disabled webworkers on my version because of some issue. 

Segmentation fault 
---

>Any thoughts on the "Segmentation fault (core dumped)" error?

Have you got the full output, as well as the error? 
I don't know of anyone reporting this error.
