### ISSUE TITLE
Theme customization question

### ISSUE THREAD

**Issue by AlejandroDagobah** [audreyt/ethercalc#774]
Hi ethercalc friends! i'm new to ethercalc and its wonderfull! i wanted to edit the look of ethercalc, but i have problems searching where the cells are created because their style is set it on ethercalc.js like this: border-bottom:"+m.borderstyles[l] but i dont know where m.borderstyles is set.

**Comment by eddyparkinson** [comment]
Try this file.   https://github.com/marcelklehr/socialcalc/blob/master/js/socialcalc-3.js
It defines and uses borderstyles 

If you look at the make file you will see how it gets imported. 

FYI  DanBricklin invented the first spreadsheet. The above is a fork of his SocialCalc spreadsheet.

**Comment by eddyparkinson** [comment]
Closing this. Let me know if you need more support with this.

**Comment by AlejandroDagobah** [comment]
thanks a lot Eddy yes i figure it out how to edit style and some buttons but i'm stuck trying to compile socialcalc to ethercalc.js it gives me this error:

```
run npm audit fix to fix them, or npm audit for details
cp node_modules/socialcalc/SocialCalc.js node_modules/socialcalc/dist/SocialCalc.js || true
cp: cannot stat 'node_modules/socialcalc/SocialCalc.js': No such file or directory
node node_modules/uglify-js/bin/uglifyjs node_modules/socialcalc/dist/SocialCalc.js third-party/class-js/lib/Class.js third-party/wiki
wyg/lib/Document/Emitter.js third-party/wikiwyg/lib/Document/Emitter/HTML.js third-party/wikiwyg/lib/Document/Parser.js third-party/wi
kiwyg/lib/Document/Parser/Wikitext.js static/jquery.js static/vex.combined.min.js static/jquery-ui.min.js -c -m --source-map ethercalc
.js.map --source-map-include-sources >> static/ethercalc.js
C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\tools\node.js:42
    sys.error("WARN: " + txt);
        ^

TypeError: sys.error is not a function
    at Function.UglifyJS.AST_Node.warn_function (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\ugli
fy-js\tools\node.js:42:9)
    at Function.AST_Node.warn (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\ast
.js:110:18)
    at Compressor.warn (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress.j
s:87:27)
    at TreeTransformer.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\com
press.js:1061:48)
    at AST_Function.transform (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\tra
nsform.js:61:35)
    at AST_Function.drop_unused (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\c
ompress.js:1169:18)
    at Compressor.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress
.js:99:18)
    at AST_Function.transform (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\tra
nsform.js:61:35)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\transform.js:197:33
    at Compressor.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress
.js:96:9)
Makefile:56: recipe for target 'static/ethercalc.js' failed
mingw32-make: *** [static/ethercalc.js] Error 1


```
it would be very nice if you could help me thanks a lot!

**Comment by eddyparkinson** [comment]
First compile socialCalc then use the socalcalc files to compile ether calc.  
I created a single makefile to do it in one go. As both make files need to run. 

Did uglify-js  fail?  it is used to compress the js files to improve load speed. It is a third party program. 


    On Tuesday, 18 January 2022, 14:05:59 GMT+10:30, AlejandroDagobah ***@***.***> wrote:  
 
 


thanks a lot Eddy yes i figure it out how to edit style and some buttons but i'm stuck trying to compile socialcalc to ethercalc.js it gives me this error:

 runnpm audit fixto fix them, ornpm audit` for details
cp node_modules/socialcalc/SocialCalc.js node_modules/socialcalc/dist/SocialCalc.js || true
cp: cannot stat 'node_modules/socialcalc/SocialCalc.js': No such file or directory
node node_modules/uglify-js/bin/uglifyjs node_modules/socialcalc/dist/SocialCalc.js third-party/class-js/lib/Class.js third-party/wiki
wyg/lib/Document/Emitter.js third-party/wikiwyg/lib/Document/Emitter/HTML.js third-party/wikiwyg/lib/Document/Parser.js third-party/wi
kiwyg/lib/Document/Parser/Wikitext.js static/jquery.js static/vex.combined.min.js static/jquery-ui.min.js -c -m --source-map ethercalc
.js.map --source-map-include-sources >> static/ethercalc.js
C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\tools\node.js:42
sys.error("WARN: " + txt);
^

TypeError: sys.error is not a function
at Function.UglifyJS.AST_Node.warn_function (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\ugli
fy-js\tools\node.js:42:9)
at Function.AST_Node.warn (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\ast
.js:110:18)
at Compressor.warn (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress.j
s:87:27)
at TreeTransformer.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\com
press.js:1061:48)
at AST_Function.transform (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\tra
nsform.js:61:35)
at AST_Function.drop_unused (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\c
ompress.js:1169:18)
at Compressor.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress
.js:99:18)
at AST_Function.transform (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\tra
nsform.js:61:35)
at C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\transform.js:197:33
at Compressor.before (C:\Users\PC\AppData\Roaming\npm\node_modules\ethercalc\node_modules\uglify-js\lib\compress
.js:96:9)
Makefile:56: recipe for target 'static/ethercalc.js' failed
mingw32-make: *** [static/ethercalc.js] Error 1
`

it would be very nice if you could help me thanks a lot!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
