### ISSUE TITLE
Despite files being there, ethercalc shows no files in _roomlinks

### ISSUE THREAD

**Issue by wiwwo** [audreyt/ethercalc#778]
Hi!
latest local copy of ethercalc
local directory:
```
-rw-rw-r-- 1 etherpad etherpad 61309 Jan 24 10:37 audit-sheet1.txt
-rw-rw-r-- 1 etherpad etherpad  9844 Jan 24 11:27 audit-sheet2.txt
-rw-rw-r-- 1 etherpad etherpad   642 Jan 24 10:37 snapshot-sheet1_formdata.txt
-rw-rw-r-- 1 etherpad etherpad  9482 Jan 24 10:37 snapshot-sheet1.txt
-rw-rw-r-- 1 etherpad etherpad  6216 Jan 24 11:30 snapshot-sheet2.txt
```
but no files shown in `_roomlinks`.
Lockily the files seem (?) to have their content, so no work lost hopefully.
But, what is going on?

**Comment by wiwwo** [comment]
p.s.: `etherpad` user is not a typo.

On a plus note: nothing changed, and suddenly it stopped working.

How do i get meaningful logs?
Which are ethercalc command line options?

**Comment by wiwwo** [comment]
Only logging i can get:
```
Please connect to: http://127.0.0.1:8001/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8001 in production mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

==> Falling back to file system storage: /opt/ethercalc-docs/dump/
(node:731) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
