### ISSUE TITLE
Multi sheets export to .ods, .xls crashes the server

### ISSUE THREAD

**Issue by Dri372** [audreyt/ethercalc#795]
On a fresh new version of ethercalc the server crashes evrytime I try to export to a .ods or .xls file.

I get these error messages :

/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:602
                throw err;
                ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ServerResponse.res.setHeader (/usr/lib/node_modules/ethercalc/node_modules/connect/lib/patch.js:133:22)
    at ServerResponse.res.set.res.header (/usr/lib/node_modules/ethercalc/node_modules/express/lib/response.js:578:10)
    at ServerResponse.res.contentType.res.type (/usr/lib/node_modules/ethercalc/node_modules/express/lib/response.js:447:15)
    at /usr/lib/node_modules/ethercalc/main.js:131:34
    at try_callback (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (node:events:513:28)
    at ReplyParser.send_reply (/usr/lib/node_modules/ethercalc/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/usr/lib/node_modules/ethercalc/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/usr/lib/node_modules/ethercalc/node_modules/redis/index.js:102:14)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
 {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.14.1

**Comment by audreyt** [comment]
Resolved by ecb18d3: multi-sheet export for xlsx/ods/fods is properly implemented in the TypeScript rewrite — walks the TOC, fetches sub-sheets, builds the workbook with per-sheet formula preservation. No server crash.
